### ISSUE TITLE
multiselect dropdown only saves last value.

### ISSUE THREAD

**Issue by bkrajendra** [rainlab/translate-plugin#115]
I'm trying to render a multiselect dropdown on backend form by using field property 
```yml
    nearby_destinations:
        label: Nearby Destinations
        type: dropdown
        attributes:
            multiple: true
```

this is properly rendering as multiselect dropdown but while saving it only saves last value to database. Ive tried to make it jsonable but still not working.
Please help!
