### ISSUE TITLE
Translate messages in theme.yaml

### ISSUE THREAD

**Issue by ribsousa** [rainlab/translate-plugin#157]
Can anyone help me how to translate messages from the theme lang, theme.yaml file?
I am following the instructions of translation plugin, but is not working!

theme.yaml

```
name: My Theme
# [...]

translate:
    en:
        site.name: 'My Website'

```

In my output

```

<h4>{{ site.name|_ }}</h4>

```
