### ISSUE TITLE
"default" option for columns is not translatable

### ISSUE THREAD

**Issue by lunfel** [rainlab/translate-plugin#235]
In the context of column definition in a plugin list, I would expect the column option "default" to be translatable. It currently does not translate and keeps the original translation string as is.

```
columns:
    name:
        label: mynamespace.myplugin::lang.columns.name
        searchable: true
        default: mynamespace.myplugin::lang.columns.name_default
```

In the list, every element that have an empty value for name willl literaly show as "mynamespace.myplugin::lang.columns.name_default" instead of the translated version of the translation string. The will label will translate correctly
