### ISSUE TITLE
MLRepeater not working with groups

### ISSUE THREAD

**Issue by munxar** [rainlab/translate-plugin#290]
Expected behavior

Add a group type X in language A and a group type Y in language B. If I switch from language A to B and back to A, the group type should be X.

Actual behavior

If the language is switched from B to A the group type is Y instead of X.
Check Video: [http://youtu.be/a633InT4pwo?hd=1](http://youtu.be/a633InT4pwo?hd=1)
(ignore audio...)

Reproduce steps

1. DB table with text columns id (PK),  content (text) 
2. Model from the table, make 'content' jsonable
3. Define columns.yaml (not important), 
4. Define fields.yaml like this:
```yaml
fields:    
    content:
        label: Content
        oc.commentPosition: ''
        prompt: 'Add new item'
        span: full
        type: repeater
        groups:
          textarea:
            name: Textarea
            description: Textarea
            icon: icon-leaf
            fields:
              textarea_content:
                label: Content
                type: richeditor
          text:
            name: Text
            description: Text
            icon: icon-leaf
            fields:
              text_content:
                label: Content
```
5. Make controller and backend menu
6. Create two languages (e.g. en (default), de)
7. Place a text in language en and set some value, place a textarea in language de and set some value -> save
8. Refresh form, switch from language en to de (group type in de is correct -> textarea), switch back to en (group type is wrong -> textarea instead of text)

October build

(419, 420)

Note: If alle languages have the same order and types of groups, everything is working as expected.
