### ISSUE TITLE
Empty fields with nested repeaters

### ISSUE THREAD

**Issue by AlanNoeOrtega** [rainlab/translate-plugin#307]
could someone help me? I got a problem using the plugin with nested repeater. I have my fields like:

[MLRepeater]
 - Textfield ROOT
 [Repeater]
   -- Text Field CHILD
   -- Rich Editor CHILD
   ...
 [/Repeater]
 [Repeater]
   -- Text Field CHILD
   -- Rich Editor CHILD
   ...
 [/Repeater]
 ...
[/MLRepeater]

When I change language, "Textfield ROOT" changes correctly, however "Text Field CHILD" appears blank, empty, even if data in DB are correct and when I print a dump($this) for MLRepeater "data" is correct. But, repeaters inside are empty. When I tried to get saved data in Frontend, Everything is right.

**Comment by yarbala** [comment]
I have same issue

**Comment by Fl0Cri** [comment]
Me too in a slightly different context. I was doing tests with https://github.com/daftspunk/oc-test-plugin
The repeater I tried to use is in the `Countries` section, in the `States` tab. It is defined like this:
```YAML
states:
    tab: States
    type: repeater
    form:
        fields:
            title:
                label: State
            item:
                type: repeater
                prompt: Add new suburb
                form:
                    fields:
                        subtitle:
                            label: Suburb
                            span: left
```

I saved these values (same in my other language except that `EN` was replaced by `FR`):
![edit countries _ octobercms - google chrome 2017-12-21 09 32 57](https://user-images.githubusercontent.com/16371551/34247255-1c8d23ae-e632-11e7-9fd2-d607d5d33148.png)

If I try to switch to my other langauge, I get 2 empty text fields inside my `Test2` node that doesn't exist in the saved data:
![edit countries _ octobercms - google chrome 2017-12-21 09 35 43](https://user-images.githubusercontent.com/16371551/34247341-6953c774-e632-11e7-804c-d5fb947111b5.png)

Switching back to the default locale also adds the empty fields.
If I don't save and reload the page, everything is correct again (until I try to switch locale).
