### ISSUE TITLE
lang.yaml issues

### ISSUE THREAD

**Issue by WebShapedBiz** [rainlab/translate-plugin#368]
Hi.

I've placed my `lang.yaml` in `config/lang.yaml` inside my theme folder. The file content looks like this:

```
translate:
    en:
      list.of.activities: 'List of activities'
      product.code: 'Product code'
      price: 'Price'
      ...
     hr:
       list.of.activities: 'Lista aktivnosti'
       ...
```
Also, I've created a link to the `lang.yaml` file inside `theme.yaml` file as instructed.

In Settings -> Translate messages "Clear cache" works but when I try to "Scan for messages", after the "Purge" dialog and whatever I do with "Purge all messages first" checkbox, I'm presented with this error:

`trim() expects parameter 1 to be string, array given in /var/www/public/plugins/rainlab/translate/models/Message.php:165`

At the same time scan did find that I've got two languages in my `lang.yaml` file thus creating two rows in Messages table, `en` and `hr`.

Am I doing something wrong? I've followed your documentation to the letter.

My installation has the latest core (4.3.4) and plugin version (1.3.8).

Thank you for your support.

Cheers.
