### ISSUE TITLE
Theme Data Translation

### ISSUE THREAD

**Issue by raquelegluu** [rainlab/translate-plugin#376]
I'm trying to translate theme customization fields extending ThemeData like I see on issue https://github.com/rainlab/translate-plugin/issues/279 for extend mail templates, but it isn't working.

In my boot method of my plugin I put this:
```
ThemeData::extend(function($model) {
    $model->implement[] = '@RainLab.Translate.Behaviors.TranslatableModel';
    $model->addDynamicProperty('translatable', ['website_data']);
});
```

The field 'website_data' is configured in theme.yaml
```
 website_data:
    type: text
    tab: Info
    label: Data Tanslatable
```

The field is printed correctly but without translation option.

Is it possible to translate this fields?? Thanks

**Comment by LukeTowers** [comment]
@raquelegluu it's possible that's not supported as all of those fields are actually collected and stored in the `data` model attribute: https://github.com/octobercms/october/blob/master/modules/cms/models/ThemeData.php#L56-L63 which might not play nice with this plugin. Feel free to investigate further.

**Comment by raquelegluu** [comment]
Thanks @LukeTowers, finally I saw it and solved it with my own event to read all translatable fields from themeData and creating my own behavior to manage data before save it.

**Comment by LukeTowers** [comment]
@raquelegluu awesome, glad to hear it! If you can make a PR to provide that ability to other people that would be fantastic!

**Comment by iboved** [comment]
@raquelegluu How did you do this? Can you give an example of how to make ThemeData fields translatable?
Thank you in advance.

**Comment by AdrienAdB** [comment]
Hi, working on same feature. Did anyone find a solution? @raquelegluu ?

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by robinbonnes** [comment]
Needed this too, fixed it by adding the following code to the `plugin.php` boot function in any existing plugin, or create a new plugin:

```
<?php namespace Acme\Translate;

class Plugin extends \System\Classes\PluginBase
{
    public function pluginDetails() 
    {
        return [
            'name'        => 'Translate Theme',
            'description' => 'With this plugin you can translate theme data.'
        ];
    }

    public function boot() 
    {
        if(!class_exists('\RainLab\Translate\Behaviors\TranslatableModel'))
            return;

        \Cms\Models\ThemeData::extend(function ($model) { 
        
            // Implement translatable model
            $model->implement[] = '@RainLab.Translate.Behaviors.TranslatableModel';
            
            // Set correct theme
            $model->theme = \Cms\Classes\Theme::getActiveThemeCode();

            // Mark all custom theme fields as translatable
            $translatable = [];
            foreach ($model->getFormFields() as $id => $field) {
                $translatable[] = $id;
                
                // Make mlrepeater jsonable
                if(isset($field['type']) && $field['type'] == 'mlrepeater') {
                    $model->addJsonable($id);
                }
            }
            
            $model->addDynamicProperty('translatable', $translatable);
        });
    }
}
```

Make sure to use the ML-prefixed formwidgets in your `theme.yaml` file, example:

```
name: Theme name
description: 'Just an example'
code: example

form:
    fields:
        text:
            type: mltext
            label: Textfield example.
        textarea:
            type: mltextarea
            label: Textarea example.
        richeditor:
            type: mlricheditor
            label: Richeditor example.
        markdown:
            type: mlmarkdowneditor
            label: Markdown editor example.
        repeater:
            type: mlrepeater
            label: Repeater example.
        mediafinder:
            type: mlmediafinder
            label: Mediafinder example.
```

Hope its useful for anyone.
