### ISSUE TITLE
How to translate default field values

### ISSUE THREAD

**Issue by Zollerboy1** [rainlab/translate-plugin#420]
As an example I have a translatable model:

```php
class Settings extends Model {
	public $implement = [
		'System.Behaviors.SettingsModel',
		'RainLab.Translate.Behaviors.TranslatableModel'
	];

	public $settingsCode = 'zollerboy_customtheme_settings';
	public $settingsFields = 'fields.yaml';

	public $translatable = [
		'site_name',
		//I have a lot more here
	];
}
```

My `fields.yaml` looks like this:

```yaml
tabs:
  fields:
    site_name:
        tab: Info
        label: Website Name
        type: text

    # And so on ...
```

Is it possible, that I give the field `site_name` a default value for each language?

I tried it with

```yaml
default: name.plugin::lang.settings.default.site_name
```
but that seems to just work with labels but not with default values.
