### ISSUE TITLE
Nested Translatable Repeater Issue

### ISSUE THREAD

**Issue by Zollerboy1** [rainlab/translate-plugin#421]
I have a translatable Repeater in my Backend form, which has nested in it another Repeater:

```yaml
skills_extra:
    tab: Skills
    prompt: Add Extra Skill
    type: repeater
    form:
        fields:
            skills_extra_line:
                label: Extra Skill
                type: section
            skills_extra_title:
                label: Extra Skill Title
                type: text
            skills_extra_list_line:
                label: Extra Skill List
                type: section
            skills_extra_list:
                prompt: Add Extra Skill List
                type: repeater
                form:
                    fields:
                        skills_extra_list_item:
                            label: Extra Skill List Item
                            type: text
```

When I now add Items to the repeater everything seems to work fine, but there is a strange Issue.

**Reproduce:**
- Add an item to the `skills_extra` repeater and add also an item to the `skills_extra_list` repeater in it.  
- Then add another item to the `skills_extra` repeater, which also has a nested item.  
- Now save the form and reload the site.
- You will see, that both items have now 2 nested items, in the first one the second nested item is empty, in the second one the first item is empty.

Imagine the case, that you have 100 items with 2 nested items each. All of a sudden each of the items would now have 200 nested items. This is independent from the different languages, but it occurs only in the translatable repeater.
