### ISSUE TITLE
Input preset converter cannot listen field of current language only

### ISSUE THREAD

**Issue by Rike-cz** [rainlab/translate-plugin#429]
##### Expected and actual behavior
When I write a title for e.g. new Blog article, I expect autogenerated slug in selected language, but I receive this same slug for all languages! As a result of this behavior there is non existing article language mutation created!
I think this issue needs deep improvement in input preset converter, or to create new solution for this Translate plugin.
![data-input-preset-bug](https://user-images.githubusercontent.com/4247582/50045032-69aae000-0084-11e9-8a6f-927fe4c02efe.gif)

This bug really need a quick fix, it breaks function of whole plugin. (I am not able to do good PR for this issue.)

**Comment by LukeTowers** [comment]
Awesome, thanks @munxar

**Comment by munxar** [comment]
what I debugged so far is, that if any (!) preset feature is used on a translatable text field, this bug happens. 
e.g.
```yaml
fields:
    name:
        label: Name
        span: left
        type: text
    slug:
        label: Slug
        span: right
        type: text
        preset:
            field: name
            type: slug
```
if *name* and *slug* are translatable, then entering text into the *name* field will write all hidden RLTranslate[x][y] fields. Because it writes all those fields, even if the default language was set, the data gets overwritten for all languages.

because there is no server side interaction, I'm pretty sure we have to fix the presets javascript code.
