### ISSUE TITLE
Switch all fields to the selected locale (by holding the CMD / CTRL key) - repeater bug

### ISSUE THREAD

**Issue by iboved** [rainlab/translate-plugin#523]
OctoberCMS Build: 458
RainLab.Translate plugin version: 1.6.2

### Description:
There is a very useful feature in this plugin - we can switch ALL multi-language Input fields to the selected locale by holding the CMD / CTRL key (don’t know why this is not the default behavior, but at the moment it is ok). So, I always use this key combination to switch all multi-language input fields, instead of switching each field separately. I have found a bug related to Repeater and switching locale by holding the CMD / CTRL key. When you switch to the same locale (by holding the CMD / CTRL key) multiple times, strange things happen with Repeater field - data from one language overwrites data from another language, some data is lost and so on. This happens only when I switch locale by holding the CMD / CTRL key. Check my steps to reproduce below.

### Steps To Reproduce:
You should have at least 2 active languages. In my case I have English (EN) and Deutsch (DE). Add any repeater field to your `fields.yaml`. Don't forget to add this field to `$jsonable` and `$translatable` arrays in your model. You can use this Repeater field for test:
```
extra_information:
    label: Extra information
    type: repeater
    form:
        fields:
            title:
                label: Title
                type: text
            description:
                label: Description
                type: textarea
```
Please add one item to this repeater only for default language (in my case this is English), fill Title and Description fields, save the model. After that press CMD / CTRL key and select another language in the repeater (in my case this is Deutsch). You will see empty repeater. This is ok, because we filled only English language and Deutsch is empty. *BUT* try again to press CMD / CTRL key and select the same language you selected before in the repeater (in my case I again selected Deutsch language). You will see that data from English was copied to German.

So, this is a simple case. If your repeater has data in both locales, the data of the second locale will be overwritten by the data of the first locale. If you double-click on the first locale (by holding CMD / CTRL key), its data may be lost.

Thanks for your help.
