### ISSUE TITLE
Adding translatable: true has no effect on theme config fields

### ISSUE THREAD

**Issue by roojai** [rainlab/translate-plugin#582]
https://github.com/rainlab/translate-plugin#theme-data-translation

I am following instructions as linked above but see no additional language options despite checking I have 3 languages enabled.

Is there a step I am missing?

**Comment by mjauvin** [comment]
Are you sure you have the latest version of Rainlab.Translate?

**Comment by roojai** [comment]
Hi Mjauvin,

Thanks for the follow up!

I can confirm that I am using 1.6.7 and I have tried a couple of my sites with no luck. 


Please see attached screen shots.
![image](https://user-images.githubusercontent.com/31172173/81881571-14e5fe80-95c3-11ea-8da8-9a35bbf383b0.png)

![image](https://user-images.githubusercontent.com/31172173/81881603-2b8c5580-95c3-11ea-8e04-76dfd37a4718.png)

![image](https://user-images.githubusercontent.com/31172173/81881684-64c4c580-95c3-11ea-8bfd-470e29139f4a.png)

**Comment by roojai** [comment]
![image](https://user-images.githubusercontent.com/31172173/81881739-82922a80-95c3-11ea-8bae-4f6d2066a939.png)

**Comment by mjauvin** [comment]
I don't know, it's working fine here. Here's my theme.yaml file:
```
name: test
description: Test Theme
author: 'Marc Jauvin'
code: test
form:
  fields:
    test:
      label: My Translatable Test Field
      translatable: true
```
![Screenshot from 2020-05-14 12-33-28](https://user-images.githubusercontent.com/2013630/81960681-51bfee80-95df-11ea-9b57-497d7ed75ff6.png)
