### ISSUE TITLE
Backend fields language switcher not showing unless I use an old approach.

### ISSUE THREAD

**Issue by RoudyTarabay** [rainlab/translate-plugin#628]
Hello everyone, 

As the title say the language switcher in the backend is not showing unless I follow [this solution](https://octobercms.com/forum/post/using-the-translate-plug-in-in-my-model-backend-form-not-working) from 6 years ago, which seems to not be consistent with the current documentation. To clarify the solution is adding the boot method written by the original poster. 

From what I understood from the documentation adding the following lines should  be enough to enable the translation:
```
public $implement = ['Rainlab.Translate.Behaviors.TranslatableModel'];
public $translatable = ['name','slug'];
```

I am new to octobercms, so I might be missing something obvious.

Thank you for your help!

Edited to clarify further.

**Comment by mjauvin** [comment]
did you add more than one language to the backend?

**Comment by RoudyTarabay** [comment]
Yes I did.

**Comment by mjauvin** [comment]
Can you paste here your model fields definition file?

**Comment by RoudyTarabay** [comment]
@mjauvin 
Sure!

```
fields:
    name:
        label: Name
        span: auto
        placeholder: Name
        required: 1
        type: text
    slug:
        label: Slug
        span: auto
        placeholder: Slug
        required: 1
        preset:
            field: name
            type: slug
        type: text

```
