### ISSUE TITLE
MLNestedForm implementation with Static Pages

### ISSUE THREAD

**Issue by daftspunk** [rainlab/translate-plugin#665]
The Static Pages implementation provided by @hwinne

## Usage example 1

Code in my layout:
```
{# Header #}
    {variable
        name="header"
        type="nestedform"
        form="~/themes/themename/config/pages/header.yaml"
        tab="Pagina"
    }{/variable}
```

The `header.yaml` file:
```
fields:

  _title:
    label: theme.themename::lang.group.header.main.label
    comment: theme.themename::lang.group.header.main.description
    type: section

  copy:
    type: nestedform
    form: ~/themes/themename/partials/elements/copy/heading/config/heading.yaml
    span: left

  image:
    label: theme.themename::lang.group.header.image.label
    type: mediafinder
    required: true
    mode: image
    span: right

  button[label]:
    label: theme.themename::lang.group.header.button.label
    commentAbove: theme.themename::lang.group.header.button.description
    type: text
    span: right
```

And then the `heading.yaml` file:
```
fields:

  _title:
    label: Tekst
    comment: Voeg een titel en tekst toe aan dit blok.
    required: true
    type: section

  heading:
    type: text
    required: true

  description:
    type: richeditor
```

## Usage example 2
I also have a settings model with multiple nested nestedforms. When implementing the translatable behavior, I get the same error as before, when I tried to open an existing page with nestedform:
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/42736463/156609382-1b755124-e77f-4cbb-a7e4-49b2a43710d1.png">

Implementation: 
```
public $implement = [
        'System.Behaviors.SettingsModel',
        '@RainLab.Translate.Behaviors.TranslatableModel',
    ];
    public $translatable = ['footer'];
```

Settings `main.yaml`:
```
tabs:
    icons:
        Footer: fal fa-rectangle-landscape

    fields:
        #
        # Footer
        #
        _section_footer:
            label: Footer
            comment: Pas de uitstraling van de footer aan.
            type: section
            tab: Footer

        footer:
            type: nestedform
            showPanel: false
            form: ~/themes/themename/partials/modules/footer/config.yaml
            tab: Footer
```

The `footer/config.yaml` contains multiple nestedforms.
