### ISSUE TITLE
Repeater data translation does not work after reload page. OctoberCMS v3

### ISSUE THREAD

**Issue by get-web** [rainlab/translate-plugin#690]
Repeater data translation does not work after reload page. OctoberCMS v3

Before reload:
![](https://raw.githubusercontent.com/get-web/Examples/main/other/rainlab-translate-plugin/before-reload.gif)

After reload:
![](https://raw.githubusercontent.com/get-web/Examples/main/other/rainlab-translate-plugin/after-reload.gif)

My fields:
```
        partners_list:
            tab: Партнеры
            type: repeater
            translatable: true
            prompt: Добавить баннер ВК
            form:
                fields:
                    title:
                        label: Заголовок
                        type: text
                        span: left
                    url:
                        label: Ссылка
                        type: text
                        span: right
                    desc:
                        label: Описание
                        type: textarea
                        span: left
                        size: small
                    img:
                        label: Логотип
                        span: right
                        type: mediafinder
                        mode: image
```
