### ISSUE TITLE
Translate dynamic dropdown options in repeater

### ISSUE THREAD

**Issue by ssi-com-pl** [rainlab/translate-plugin#710]
Hi! I use dropdown field in repeater to create a list of places. Places are added in the backend. How to display translated place names on the frontend?

```
        places:
            label: 'Places nearby'
            style: accordion
            span: left
            type: repeater
            tab: 'Places nearby'
            form:
                fields:
                    place:
                        label: Place
                        span: auto
                        showSearch: true
                        type: dropdown
                    distance:
                        label: 'Distance (m)'
                        span: auto
                        type: text
                    place_address:
                        label: 'Address'
                        span: full
                        type: text

```

```
    public function getPlaceOptions(){
		return Place::orderBy('name')->lists('name','name');
	}
```

![image](https://user-images.githubusercontent.com/57666038/210063604-855c79ca-1db9-46a1-b118-e06a4e885758.png)
![image](https://user-images.githubusercontent.com/57666038/210063734-5e735058-cf98-45f0-8163-c6a76fc61270.png)
![image](https://user-images.githubusercontent.com/57666038/210063764-10dc7993-3b30-4157-a94b-029f611f5b1a.png)
![image](https://user-images.githubusercontent.com/57666038/210064246-eb5aa35c-9f31-4d3b-b066-c2152883a905.png)
